version: '3.1'
services:
  db:
    image: mysql
    restart : always
    environment:
      MYSQL_DATABASE: db_istic_tp_taa
      MYSQL_USER: artkoto
      MYSQL_PASSWORD: Akoto
      MYSQL_ROOT_PASSWORD: Akoto
    ports:
      # just if you also want to access it directly from you host
      # node neede for phpmyadmin
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"